version: '3.7'

services:
  {% for service in services -%}
  {{service.service_name}}:
    {% if service.env_files -%}
    env_file:
      {% for envfile in service.env_files -%}
      - {{envfile}}
      {%- endfor %}
    {%- endif %}
    build:
      context: {{service.path_absolute}}
      dockerfile: {{service.dockerfile_absolute}}
    volumes:
      - type: bind
        source: {{service.path_absolute}}
        target: /code
    {% if service.dependencies or service.resources -%}
    depends_on:
      {% for dep in service.dependencies -%}
      - {{dep}}
      {% endfor -%}
      {% for rname, resource in service.resources.items() -%}
      - {{resource.name}}
      {%- endfor %}
    {%- endif %}
    restart: always
    image: {{service.service_name}}
    ports:
      - {{service.container_port}}
    {% if service.command -%}
    command: {{service.command}}
    {%- endif %}
  {% for rname,resource in service.resources.items() -%}
  {% if resource.type == "database" and resource.engine == "postgres" -%}
  {{resource.name}}:
    image: postgres:latest
    env_file:
      - {{resource.env_file}}
    # volumes:
    #   - ./postgres-data:/var/lib/postgresql/data   
  {%- endif %}
  {%- endfor %}
  {%- endfor %}
