sudo: required
dist: xenial

language: python
python:
- '3.7'
cache: pip

services:
- docker

jobs:
  include:
  - stage: test
    before_install: bash scripts/travis/before_install.sh
    install: true
    script: bash scripts/travis/script.sh
