version: '3.7'

x-web-environment:
  &web-environment
  environment:
    - PORT=8000
    - ENVIRONMENT_NAME=local_dev
    - USING_DOCKER_COMPOSE=true
    - DJANGO_SETTINGS_MODULE=config.settings.local
    - DJANGO_CONFIGURATION=Local
    - DJANGO_SECRET_KEY
    - DJANGO_ALLOWED_HOSTS
    - DJANGO_CORS_ORIGIN_WHITELIST
    - DJANGO_ADMIN_URL=real-admin
  build:
    context: ./
    dockerfile: Dockerfile.local
  volumes:
    - type: bind
      source: ./
      target: /code
  depends_on:
    - postgres
    - redis

services:
  postgres:
    image: postgres:alpine

  redis:
    image: redis:alpine

  web:
    <<: *web-environment
    restart: always
    image: web
    ports:
      - "8000:8000"
    command: scripts/local/run_web.sh

  celery:
    <<: *web-environment
    restart: always
    command: scripts/local/run_celery.sh

  celery-beat:
    <<: *web-environment
    restart: always
    command: scripts/local/run_celery_beat.sh
