FROM python:3.7-buster
ENV PYTHONUNBUFFERED 1

# Adds our application code to the image
copy . /code/
WORKDIR /code

RUN pwd

RUN pip install -r requirements.txt && pip install pyinstaller

ENTRYPOINT "docker/scripts/release.sh"
