name: Codebuild release ecr

on:
  push:
    branches: [dev, add-nextjs-service-type]

jobs:

  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
            repository: 'diggerhq/codebuild-runner'
            token: ${{ secrets.TOKEN_FOR_REPO_CLONE }}

      - name: initialize awscli
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.STAGING_AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: build and push to ecr
        run: |
            export TAG=$(git rev-parse --short "$GITHUB_SHA")
            export AWS_ACCESS_KEY_ID=${{ secrets.STAGING_AWS_KEY_ID }}
            export AWS_SECRET_ACCESS_KEY=${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 682903345738.dkr.ecr.us-east-1.amazonaws.com/codebuild-runner
            docker build -t codebuild-runner .
            docker tag "codebuild-runner:dev" "682903345738.dkr.ecr.us-east-1.amazonaws.com/codebuild-runner:$TAG"
            docker push "682903345738.dkr.ecr.us-east-1.amazonaws.com/codebuild-runner:$TAG"
            docker push "682903345738.dkr.ecr.us-east-1.amazonaws.com/codebuild-runner:dev"
