name: Codebuild release ecr for dev

on:
  push:
    branches: [dev**]

jobs:

  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
            repository: 'diggerhq/codebuild-runner'
            token: ${{ secrets.TOKEN_FOR_REPO_CLONE }}

      - name: Configure Staging AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to STAGING Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: build and push to ecr
        run: |
            export TAG=$(git rev-parse --short "$GITHUB_SHA")
            docker build --build-arg TAG=$TAG -t 682903345738.dkr.ecr.us-east-1.amazonaws.com/codebuild-runner:dev -t 682903345738.dkr.ecr.us-east-1.amazonaws.com/codebuild-runner:$TAG .
            docker push "682903345738.dkr.ecr.us-east-1.amazonaws.com/codebuild-runner:$TAG"
            docker push "682903345738.dkr.ecr.us-east-1.amazonaws.com/codebuild-runner:dev"
