name: Codebuild release ecr

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:

  get-tag-version:
    name: Get tag version
    outputs:
      tag_version: ${{ steps.get_version.outputs.VERSION }}

    runs-on: ubuntu-latest
    steps:
      - name: Get the tag version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

  build-and-release:
    needs: get-tag-version
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
            repository: 'diggerhq/codebuild-runner'
            token: ${{ secrets.TOKEN_FOR_REPO_CLONE }}

      - name: initialize awscli
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: build and push to ecr
        run: |
            export TAG=${{needs.get-tag-version.outputs.tag_version}}
            export AWS_ACCESS_KEY_ID=${{ secrets.AWS_KEY_ID }}
            export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws ecr-public get-login-password --region us-east-1  | docker login --username AWS --password-stdin 739940681129.dkr.ecr.us-east-2.amazonaws.com/codebuild-runner
            docker build --build-arg TAG=$TAG -t dg -f docker/Dockerfile.ecr.publish .
            docker tag "dg:latest" "739940681129.dkr.ecr.us-east-2.amazonaws.com/codebuild-runner:$TAG"
            docker tag "dg:latest" "739940681129.dkr.ecr.us-east-2.amazonaws.com/codebuild-runner:latest"
            docker push "739940681129.dkr.ecr.us-east-2.amazonaws.com/codebuild-runner:latest"
            docker push "739940681129.dkr.ecr.us-east-2.amazonaws.com/codebuild-runner:$TAG"
