name: Package for mac

on: 
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest] 
    steps:
    - uses: actions/checkout@v1

    - name: perform pyinstaller build
      run: ./scripts/buildformac.sh

    - uses: actions/upload-artifact@v2
      with:
        name: dg
        path: src/dist/mac
